name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
      working-directory: ../cafe-don-emilio  # Cambiado a la ubicación correcta
    - name: Build
      run: yarn build
      working-directory: ../cafe-don-emilio  # Cambiado a la ubicación correcta
    - name: Run Tests
      run: yarn test
      working-directory: ../cafe-don-emilio  # Cambiado a la ubicación correcta
